// Autogenerated from Pigeon (v0.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

extern NSDictionary* wrapResult(NSDictionary *result, FlutterError *error);
extern NSDictionary* wrapResult2(NSArray *result, FlutterError *error);

@class PiLocale;

@interface PiLocale : NSObject
@property(nonatomic, copy, nullable) NSString * languageCode;
@property(nonatomic, copy, nullable) NSString * countryCode;
@property(nonatomic, copy, nullable) NSString * scriptCode;
-(NSDictionary*)toMap;
@end

@protocol PlatformLocale
-(nullable PiLocale *)_currentLocale:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void PlatformLocaleSetup(id<FlutterBinaryMessenger> binaryMessenger, id<PlatformLocale> _Nullable api);

NS_ASSUME_NONNULL_END
